### ISSUE TITLE
Error   IBM Cloud Deploy / deploy   

### ISSUE THREAD

**Issue by shenchihua** [fcying/IBMYes#11]
154   Updating app ***...
155   Mapping routes...
156   Comparing local files to remote cache...
157   Packaging files to upload...
158   Uploading files...
159   
160   The app is invalid: Invalid application source code found
161   0 B / 1.27 KiB    0.00%FAILED
162   ##[error]Process completed with exit code 1.

**Comment by LikChung** [comment]
I have the same problem. Any solution?

**Comment by yiailake** [comment]
![image](https://user-images.githubusercontent.com/5363570/92895520-24306800-f44e-11ea-8722-2c01d67bee94.png)

**Comment by fcying** [comment]
现在 ibm 开始检测 是否有v2ray了. 需要改名字后使用. 
https://github.com/fcying/IBMYes/issues/8
