### ISSUE TITLE
Some error print when deploy actions

### ISSUE THREAD

**Issue by biozzl** [fcying/IBMYes#17]
Run ./deploy.sh
  ./deploy.sh
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    IBM_ACCOUNT: ***
    RESOURSE_ID: 
    IBM_APP_NAME: ***
    IBM_MEMORY: ***
    BIN_NAME: ***
    V2_ID: ***
    V2_PATH: ***
    ALTER_ID: ***
Saved in /home/runner/.bluemix/tmp/cf_005572877/cf-cli_6.51.0_linux_x86-64.tgz
Installing Cloud Foundry CLI...
OK
Cloud Foundry CLI is successfully installed
cf login===================================
API endpoint: https://api.us-south.cf.cloud.ibm.com

Email: ***

Password: 
Authenticating...
OK

Targeted org ***

Targeted space dev

API endpoint:   https://api.us-south.cf.cloud.ibm.com (API version: 3.87.0)
User:           ***
Org:            ***
Space:          dev
cf push===================================
Pushing from manifest to org *** / space dev as ***...
Byte quantity must be a positive integer with a unit of measurement like M, MB, G, or GB
Using manifest file /home/runner/work/IBMYes-new/IBMYes-new/***/manifest.yml
FAILED
print error===================================
Retrieving logs for app *** in org *** / space dev as ***...

**Comment by fcying** [comment]
IBM_MEMORY 设错了吧...是不是后面的M 忘写了...

**Comment by biozzl** [comment]
Thank you! now it's working perfectly fine.
