### ISSUE TITLE
一个账号多APP部署的workflow修改问题

### ISSUE THREAD

**Issue by PaTTeeL** [fcying/IBMYes#19]
我试着修改了deploy.sh和ibm.yml，结果发现执行workflow之后更新了3遍app1，后面的app2和app3动都没动，请问大神还要修改哪些地方啊？

增加和修改的代码如下：
deploy.sh
-----------------------------------
mkdir -p $IBM_APP_NAME2
mkdir -p $IBM_APP_NAME3

# cloudfoundry2 config
cp -rvf ./config/manifest.yml ./$IBM_APP_NAME2/
sed "s/IBM_APP_NAME/${IBM_APP_NAME2}/" ./$IBM_APP_NAME2/manifest.yml -i
sed "s/IBM_MEMORY/${IBM_MEMORY2}/" ./$IBM_APP_NAME2/manifest.yml -i

# v2ray2 config
cp -vf ./config/v2ray ./$IBM_APP_NAME2/$IBM_APP_NAME2
cp -vf ./config/v2ctl ./$IBM_APP_NAME2/
{
    echo "#! /bin/bash"
    echo "wget https://raw.githubusercontent.com/$GITHUB_REPOSITORY/master/config/config.json"
    echo "sed 's/V2_ID/$V2_ID2/' config.json -i"
    echo "sed 's/V2_PATH/$V2_PATH2/' config.json -i"
    echo "sed 's/ALTER_ID/$ALTER_ID2/' config.json -i"

} > ./$IBM_APP_NAME2/d.sh
chmod +x ./$IBM_APP_NAME2/d.sh

# cloudfoundry3 config
cp -rvf ./config/manifest.yml ./$IBM_APP_NAME3/
sed "s/IBM_APP_NAME/${IBM_APP_NAME3}/" ./$IBM_APP_NAME3/manifest.yml -i
sed "s/IBM_MEMORY/${IBM_MEMORY3}/" ./$IBM_APP_NAME3/manifest.yml -i

# v2ray3 config
cp -vf ./config/v2ray ./$IBM_APP_NAME3/$IBM_APP_NAME3
cp -vf ./config/v2ctl ./$IBM_APP_NAME3/
{
    echo "#! /bin/bash"
    echo "wget https://raw.githubusercontent.com/$GITHUB_REPOSITORY/master/config/config.json"
    echo "sed 's/V2_ID/$V2_ID3/' config.json -i"
    echo "sed 's/V2_PATH/$V2_PATH3/' config.json -i"
    echo "sed 's/ALTER_ID/$ALTER_ID3/' config.json -i"

} > ./$IBM_APP_NAME3/d.sh
chmod +x ./$IBM_APP_NAME3/d.sh

cd ./$IBM_APP_NAME2
#echo "${BLUE}ibmcloud cf push${END}"
#$IBMCLOUD cf push
echo "${BLUE}cf push${END}"
$CF push

cd ./$IBM_APP_NAME3
#echo "${BLUE}ibmcloud cf push${END}"
#$IBMCLOUD cf push
echo "${BLUE}cf push${END}"
$CF push

if [ $? -ne 0 ]; then
    echo "${BLUE}print error${END}"
    $CF logs $IBM_APP_NAME --recent
    $CF logs $IBM_APP_NAME2 --recent
    $CF logs $IBM_APP_NAME3 --recent
    exit 1
fi
==================================

ibm.yml 
----------------------------------------------------------
  IBM_APP_NAME2: ${{ secrets.IBM_APP_NAME2 }}
  IBM_MEMORY2: ${{ secrets.IBM_MEMORY2 }}
  V2_ID2: ${{ secrets.V2_ID2 }}
  V2_PATH2: ${{ secrets.V2_PATH2 }}
  ALTER_ID2: ${{ secrets.ALTER_ID2 }}
  IBM_APP_NAME3: ${{ secrets.IBM_APP_NAME3 }}
  IBM_MEMORY3: ${{ secrets.IBM_MEMORY3 }}
  V2_ID3: ${{ secrets.V2_ID3 }}
  V2_PATH3: ${{ secrets.V2_PATH3 }}
  ALTER_ID3: ${{ secrets.ALTER_ID3 }}
--------------------------------------------------------

**Comment by fcying** [comment]
进到 app1 目录 push完后, 要去app2目录push, cd ../app2
你这3次push 都在app1 目录跑的

**Comment by PaTTeeL** [comment]
懂了，我傻了，少了cd ..，感谢~
