### ISSUE TITLE
actions报错

### ISSUE THREAD

**Issue by bk1412** [fcying/IBMYes#21]
Installing Cloud Foundry CLI...
OK
Cloud Foundry CLI is successfully installed
cf login===================================
./deploy.sh: line 91: /home/runner/.bluemix/cfcli/cf: No such file or directory
./deploy.sh: line 99: /home/runner/.bluemix/cfcli/cf: No such file or directory
cf push===================================
print error===================================
./deploy.sh: line 103: /home/runner/.bluemix/cfcli/cf: No such file or directory

没有找到对应路径

**Comment by bal1001** [comment]
我跟你一样。检查了几次设置应该没错啊。。。求解惑

**Comment by qqxing12** [comment]
一毛一样
./deploy.sh: line 91: /home/runner/.bluemix/cfcli/cf: No such file or directory
cf login===================================
./deploy.sh: line 99: /home/runner/.bluemix/cfcli/cf: No such file or directory
./deploy.sh: line 103: /home/runner/.bluemix/cfcli/cf: No such file or directory
cf push===================================
print error===================================
Error: Process completed with exit code 1.

**Comment by fcying** [comment]
IBM 又更新了...我研究下

**Comment by fcying** [comment]
新版本cf 修改了路径, 已更新
