### ISSUE TITLE
Errors when deploy run the workflow at IBM cloud interface

### ISSUE THREAD

**Issue by biozzl** [fcying/IBMYes#4]
类型
实例
日志
时间
APP/PROC/WEB	0	2020/09/09 04:00:43 Using config from env: /home/vcap/app/v2ray/config.json	
2020年9月9日 下午12:00:43
APP/PROC/WEB	0	2020/09/09 04:06:36 Using config from env: /home/vcap/app/v2ray/config.json	
2020年9月9日 下午12:06:36

**Comment by fcying** [comment]
现在 ibm 开始检测 是否有v2ray了. 需要改名字后使用. 
https://github.com/fcying/IBMYes/issues/8
