### ISSUE TITLE
Errors when deploy

### ISSUE THREAD

**Issue by biozzl** [fcying/IBMYes#8]
cf push===================================
Pushing from manifest to org *** / space dev as ***...
Using manifest file /home/runner/work/IBMYes-new/IBMYes-new/v2ray-cloudfoundry/manifest.yml
Getting app info...
Updating app with these attributes...
  name:                ***
  path:                /home/runner/work/IBMYes-new/IBMYes-new/v2ray-cloudfoundry
  command:             ./v2ray/v2ray
  disk quota:          1G
  health check type:   port
  instances:           1
  memory:              256M
  stack:               cflinuxfs3
  routes:
    ***.us-south.cf.appdomain.cloud

Updating app ***...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...

 0 B / 1.28 KiB    0.00%
The app is invalid: Invalid application source code found
 1.28 KiB / 1.28 KiB  100.00%FAILED
##[error]Process completed with exit code 1.

**Comment by kugooer** [comment]
遇到同样的问题。

**Comment by han7299** [comment]
我也这样，是不是重启更新脚本都废了。。。。

**Comment by jimmy-tsui** [comment]
检查账号吧，IBM扫代码，含有v2ray代码不让push，我已经被封号。

**Comment by wangzhiyong2019** [comment]
我也被封了

**Comment by fcying** [comment]
如果没被封号的话. 
可以把v2ray, 改个名字. 比如bin, 就可以继续用. 晚点改下脚本

**Comment by fcying** [comment]
更新了脚本. 加了个变量 APP_NAME. 会把v2ray 重命名成这个用....目前跑的正常....后续....不知道会不会扫的更严...

另外 为了方便本地测试, 把IBM_ACCOUNT拆成IBM_ACCOUNT和IBM_PASSWORD 2个了

**Comment by sp42** [comment]
> 更新了脚本. 加了个变量 APP_NAME. 会把v2ray 重命名成这个用....目前跑的正常....后续....不知道会不会扫的更严...

脚本哪里下？

**Comment by fcying** [comment]
@sp42 就是这个仓库. 同步到最新的就好了
